import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./Components/footer";
import Header from "./Components/header";
import Contact from "./Components/contact";
import Hero_section from "./Components/Hero_section";
const inter = Inter({ subsets: ["latin"] });
import ThinkIndiaInfo from "./Components/AboutThinkIndia";
import Team from "./Components/Team";
import 'aos/dist/aos.css';
export const metadata = {
  title: "Think India NextJs",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-slate-900`}>
        {children}
        </body>
    </html>
  );
}
